# Generated by Django 4.1.7 on 2023-03-13 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='calendar',
        ),
        migrations.AddField(
            model_name='appointment',
            name='car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.car'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.IntegerField(choices=[(9, '9:00 AM'), (12, '12:00 PM'), (15, '3:00 PM')], default=9),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', editable=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
